name: "1 - Hello World and Get My IP"

# I wish we didn't need to duplicate the inputs...
# Related:
# https://github.com/actions/runner/issues/1182
# https://github.community/t/inconsistent-inputs-context-for-workflow-dispatch-and-workflow-call/207835
# https://github.community/t/workflow-dispatch-and-workflow-call-at-the-same-time/225375

on: 
  # Allow calling directly
  workflow_dispatch:
    inputs:
      name:
        description: "User's name"     
        required: true
        type: string
  # Allow calling from another action
  workflow_call:
    inputs:
      name:
        description: "User's name"     
        required: true
        type: string
        
jobs:
  say_hi:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Hello ${{ (github.event.inputs || inputs).name }}!"
        
  get_this_ip:
    runs-on: ubuntu-latest
    outputs:
      ip: ${{ steps.get_ip.outputs.ip }} 
    steps:
    - id: get_ip
      run: |
        ip=$(curl https://ipinfo.io/ip)
        echo "Shhh the ip is ${ip}"
        echo "::set-output name=ip::${ip}" 
        
  print_this_ip:
    runs-on: ubuntu-latest
    needs: get_this_ip
    steps:
    - run: |
        echo "The ip was: ${{ needs.get_this_ip.outputs.ip }}"
      
