# This is a basic workflow to help you get started with Actions

name: Test1

on: 
  workflow_dispatch:
    inputs:
      name:
        description: "User's name"     
        required: true
        
jobs:
  say_hi:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Hello ${{ github.event.inputs.name }}!"
        
  get_this_ip:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "::set-output name=ip::$(curl https://ipinfo.io/ip)" 
        
  print_this_ip:
    runs-on: ubuntu-latest
    needs: get_this_ip
    steps:
    - run: |
        echo "The ip was: ${{ needs.get_this_ip.outputs.ip }}"
      
