name: "What Version Of Python is In There?"

on: 
  workflow_dispatch:
    inputs:
      docker_image:
        type: choice
        description: "System Type to Use"
        options:
          - centos
          - ubuntu
          - alpine
          - busybox
          - debian
          - amazonlinux
          - clearlinux
          - python
       
jobs:
  get_python_info:
    runs-on: ubuntu-latest
    container:  "${{ github.event.inputs.docker_image }}"
    outputs:
      python_path: ${{ steps.get_python_info.python_info.python_path }}
      python_version: ${{ steps.get_python_info.python_info.python_version }}
    steps:
      - id: python_info
        shell: bash
        run: |
          PY_P="$(which python3 2>/dev/null || which python 2>/dev/null)"
          echo "::set-output name=python_path::${PY_P}" 
          if [[ -n ${PY_P} ]]; then 
            PY_VER=$("${PY_P}" --version 2>&1)
            echo "::set-output name=python_version::${PY_VER}" 
          fi
      
  print_python_info:
    runs-on: ubuntu-latest
    needs: get_python_info
    if: ${{ needs.get_python_info.outputs.python_path }} != ""
    steps:
    - run: |
        echo "Python was found here: ${{ needs.get_python_info.outputs.python_path }}"
        echo "${{ needs.get_python_info.outputs.python_version }}"
     

      
    
