# This is a basic workflow to help you get started with Actions

name: "1 - Hello World and Get My IP"

on: 
  workflow_dispatch:
    inputs:
      name:
        description: "User's name"     
        required: true
        
jobs:
  say_hi:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Hello ${{ github.event.inputs.name }}!"
        
  get_this_ip:
    runs-on: ubuntu-latest
    outputs:
      ip: ${{ steps.get_ip.outputs.ip }} 
    steps:
    - id: get_ip
      run: |
        ip=$(curl https://ipinfo.io/ip)
        echo "Shhh the ip is ${ip}"
        echo "::set-output name=ip::${ip}" 
        
  print_this_ip:
    runs-on: ubuntu-latest
    needs: get_this_ip
    steps:
    - run: |
        echo "The ip was: ${{ needs.get_this_ip.outputs.ip }}"
      
